// ============ VISION & NORTH STAR ============
export const VISION_90 = "By May 2026, Julia's system runs autonomously, we have 2 paying clients, and outreach generates 3+ discovery calls per week.";
export const YEAR_GOAL = "By Dec 2026 — 10 paying clients, $100K+ revenue, Quietly is the go-to AI automation partner for Montreal professional services.";
export const NORTH_STAR = { label: "Conversations started", icon: "💬", description: "Two-way conversations with potential clients this week" };
export const EXPERIMENTS_META = { label: "Experiments run", icon: "🧪", description: "Outreach variations, pitch tests, process tweaks tried this week" };

export const START_DATE = "2026-02-11";

export const ROADMAP = [
  { month:"Feb", label:"Foundation", status:"now", focus:"Legal, Julia discovery call, LinkedIn profiles set up, first experiments",
    milestone:"Partnership signed. Julia build started. LinkedIn profiles live." },
  { month:"Mar", label:"First proof", status:"future", focus:"Julia build complete, case study written, outreach engine running daily",
    milestone:"Julia system live. 200+ outreach messages sent. 3–5 discovery calls booked." },
  { month:"Apr", label:"Pipeline", status:"future", focus:"Close first paying client, refine pitch from call learnings, content rhythm",
    milestone:"1 paying client ($8K+). 3 LinkedIn posts/week. Repeatable outreach process." },
  { month:"May", label:"Traction", status:"future", focus:"Second client, Julia case study driving inbound, refine delivery process",
    milestone:"2 paying clients. Julia runs autonomously. 3+ calls/week from outreach." },
  { month:"Jun–Aug", label:"Scale", status:"future", focus:"Hire help or systematize delivery, expand to clinics, raise prices",
    milestone:"4–5 clients. $50K+ cumulative revenue. Second vertical explored." },
  { month:"Sep–Dec", label:"Authority", status:"future", focus:"Inbound leads from content, referrals, known name in Montreal RE/clinic AI",
    milestone:"10 clients. $100K+ revenue. Quietly is the go-to." },
];

export const metrics = [
  { label:"Conversations started", icon:"💬", target:"20" },
  { label:"Experiments run", icon:"🧪", target:"30" },
  { label:"Proposals sent", icon:"📝", target:"2" },
  { label:"Revenue closed", icon:"💰", target:"$8K" },
];

export const catColors = {
  outreach:"#3b82f6", positioning:"#a855f7", product:"#22c55e", process:"#f59e0b", content:"#ec4899", psychology:"#14b8a6"
};

// ============ DAILY EXPERIMENTS ============
// 60 experiments, 2 per day = 30-day rotation. Each is specific enough to run in <30 min.
export const experimentBank = [
  // ===== PHASE 1: FOUNDATION (Days 0-13) — Setup before execution =====
  { id:"f1", owner:"Annie", phase:1, cat:"positioning", title:"Write your LinkedIn headline — test 3 versions",
    hyp:"The headline is the first thing anyone sees. Transformation statement outperforms job title.",
    action:"Write 3: (A) 'Cofounder @ Quietly — AI Automation' (B) 'I build AI systems that handle the work you hate' (C) 'Psychology grad turned AI builder.' Ask 3 people which makes them want to click.",
    measure:"Which gets the most 'tell me more'? Pick that one.",
    credit:"📕 DOAC Law 18 — First 5 Seconds" },
  { id:"f2", owner:"Annie", phase:1, cat:"positioning", title:"Write your LinkedIn About section",
    hyp:"Story-first outperforms resume-style.",
    action:"Mini story: (1) Dion drowning in admin (2) You combined psych + tech (3) Quietly handles the boring stuff (4) CTA: 'If you're curious, let's talk.' Under 200 words.",
    measure:"Read aloud. Would a stranger get what you do in 10 seconds?",
    credit:"📕 DOAC Law 7 — Self-Story + StoryBrand" },
  { id:"f3", owner:"Annie", phase:1, cat:"content", title:"Profile photo + banner image",
    hyp:"Visual first impression — professional but human > corporate headshot.",
    action:"Approachable photo (not modeling shot — creates distance). Canva banner that shows what Quietly does at a glance.",
    measure:"Ask 3 people: 'What does this person do?' in 3 seconds. Can't answer? Iterate.",
    credit:"📕 DOAC Law 15 — The Frame Matters" },
  { id:"f4", owner:"Annie", phase:1, cat:"content", title:"Write + publish your intro post",
    hyp:"Honest 'here's who I am' posts work because people root for founders.",
    action:"Post: 'I'm Annie. Psych degree from McGill, modeled 10 years, became a broker, now building AI with my husband. Here's why...' End with a question.",
    measure:"Impressions, comments, connection requests in 48hrs. This is your baseline.",
    credit:"📕 DOAC Law 7 — Self-Story" },
  { id:"f5", owner:"Annie", phase:1, cat:"positioning", title:"Connect with 50 target prospects",
    hyp:"You need audience before testing anything. 50 right people > 500 random.",
    action:"Search: Montreal RE brokers, PMs, clinic owners. 50 connection requests with short personal note (NOT a pitch): 'Building in [their space] in Montreal, would love to connect.'",
    measure:"Acceptance rate. Aim 40%+. Below 30% = profile needs work.",
    credit:"📕 DOAC Law 1 — Fill Your Five Buckets" },
  { id:"f6", owner:"Annie", phase:1, cat:"content", title:"Build a swipe file — study 5 founders who post well",
    hyp:"Understanding what works saves weeks of trial and error.",
    action:"Find 5 small agency/service founders with strong LinkedIn. Save 3 high-engagement posts each. Note: hook style, length, story vs insight, CTA format.",
    measure:"Swipe file created? Top 3 formats identified to try first?",
    credit:"📕 DOAC Law 19 — Sweat the Small Stuff" },
  { id:"f7", owner:"Annie", phase:1, cat:"psychology", title:"Define your 3 content pillars",
    hyp:"3 clear topics = memorable and followable. Everything = confusing.",
    action:"Pick 3: (1) Building Quietly — founder journey (2) AI for RE/clinics — expertise (3) Psychology of work — unique angle. Write 2 post ideas per pillar.",
    measure:"Can you say what you post about in one sentence?",
    credit:"📕 DOAC Law 11 — Avoid Wallpaper" },
  { id:"f8", owner:"Annie", phase:1, cat:"content", title:"Draft your 3-touch outreach DM sequence",
    hyp:"Writing before you need it = sending from calm, not desperation.",
    action:"(1) Warm intro, no pitch, one question (2) 3 days later: share something useful (3) 7 days later: soft ask for 15-min chat. Get Dion's feedback.",
    measure:"Read aloud. Human or template? Would YOU reply?",
    credit:"📕 DOAC Law 3 — Open With Common Ground" },
  { id:"f9", owner:"Annie", phase:1, cat:"positioning", title:"Set posting schedule + batch first week",
    hyp:"Consistency > frequency. 3x/week sustainable beats daily burnout.",
    action:"Pick 3 days + times. Calendar block. Set reminders. Write week 1's 3 posts in one sitting.",
    measure:"Posts written and scheduled? Decision fatigue removed?",
    credit:"📗 Atomic Habits — Implementation Intentions" },
  { id:"f10", owner:"Annie", phase:1, cat:"psychology", title:"Write your private 'why' anchor",
    hyp:"Knowing WHY sustains you through the cringe of early posting.",
    action:"Write privately: Why Quietly? What does it mean? What person do I want to become? Not for posting — your anchor on bad days.",
    measure:"Does it make you feel something? Would it pull you forward?",
    credit:"📕 DOAC Law 22 — Plan-A Thinker + 📗 Atomic Habits — Identity" },
  { id:"f11", owner:"Dion", phase:1, cat:"outreach", title:"Audit your LinkedIn for broker credibility",
    hyp:"9 years as a broker IS the credibility. Lead with that.",
    action:"Headline: '9 years in RE → now building AI for the admin I used to drown in.' About = your real story. Add broker experience prominently.",
    measure:"Ask a broker friend: 'Would you trust this person to get your problems?'",
    credit:"📕 DOAC Law 26 — Your Context Is Valuable" },
  { id:"f12", owner:"Dion", phase:1, cat:"outreach", title:"Map your existing broker network",
    hyp:"Warm outreach is 5-10x more effective than cold.",
    action:"Phone + LinkedIn + old email. List every RE person you know. Star top 10 closest — these are first conversations, not cold outreach.",
    measure:"How many names? Target: 20+.",
    credit:"📕 DOAC Law 1 — Five Buckets" },
  { id:"f13", owner:"Dion", phase:1, cat:"outreach", title:"3 coffee chats with broker friends",
    hyp:"Before pitching anyone, understand pain from people who'll be honest.",
    action:"Call 3 friends. Not a pitch: 'Can I pick your brain? Building something, want to solve a real problem.' Ask: biggest admin headache? What've you tried? What would you pay?",
    measure:"Write their exact words — this becomes your outreach language.",
    credit:"Mom Test + 📕 DOAC Law 6 — Ask, Don't Tell" },
  { id:"f14", owner:"Dion", phase:1, cat:"product", title:"Prepare Julia discovery call questions",
    hyp:"Structured questions get 10x better answers than winging it.",
    action:"Write 10 questions: current process, frustrations, time spent, what's been tried, what a good outcome looks like, budget signals. Review with Annie.",
    measure:"Questions written? Would they reveal real pain vs polite answers?",
    credit:"Mom Test + Running Lean" },
  { id:"f15", owner:"Dion", phase:1, cat:"product", title:"Document what you've already built",
    hyp:"You've built more than you think. Make it visible.",
    action:"Screenshot every workflow, integration, automation. Explain in plain language. This IS the case study even without a client yet.",
    measure:"Folder created with 5+ screenshots + descriptions?",
    credit:"📕 DOAC Law 26 — Your Context Is Valuable" },
  { id:"f16", owner:"Dion", phase:1, cat:"positioning", title:"Write 1-page 'Julia demo doc'",
    hyp:"Visual summary converts better than verbal pitch.",
    action:"One page: Problem → Solution (3 screenshots) → Outcome (hours saved) → Next step (book a call). Export as PDF.",
    measure:"Could a broker understand it without you explaining?",
    credit:"StoryBrand + 📕 DOAC Law 13 — Show, Don't Tell" },
  { id:"f17", owner:"Dion", phase:1, cat:"outreach", title:"Test 3 cold email subject lines",
    hyp:"Subject line determines open rate. Pain > benefit > curiosity.",
    action:"A: 'Question about your filing workflow' B: 'I used to drown in OACIQ forms too' C: 'Quick automation idea for [Company]'. Send 10 each, track opens.",
    measure:"Open rate comparison. Keep the winner.",
    credit:"📕 DOAC Law 18 — First 5 Seconds" },
  { id:"f18", owner:"Dion", phase:1, cat:"product", title:"Create a 2-minute Loom demo",
    hyp:"2-min video > 2-page doc for visual learners.",
    action:"Screen record: 'Here's what happens when you send a signed document...' Show the automation in action. No polishing — real is better.",
    measure:"Video done? Under 2 min? Would a broker watch the whole thing?",
    credit:"📕 DOAC Law 13 — Show, Don't Tell" },
  { id:"f19", owner:"Dion", phase:1, cat:"psychology", title:"Write your 'unfair advantage' story",
    hyp:"Story of WHY you matters more than features.",
    action:"2-paragraph version: 9 years in real estate, drowning in admin, built my way out. Not 'I built software' — 'I solved my own problem and I'll solve yours.'",
    measure:"Read aloud. Does it make you want to work with this person?",
    credit:"📕 DOAC Law 7 — Self-Story + 📕 DOAC Law 26" },
  { id:"f20", owner:"Dion", phase:1, cat:"process", title:"Define Quietly service packages",
    hyp:"Clear tiers = easier sales conversations.",
    action:"Write 2 tiers: (1) Quick Win — specific automation, flat fee (2) Full System — discovery + build + training, monthly. Price range for each.",
    measure:"Could you quote these to Julia today?",
    credit:"Value-Based Fees (Alan Weiss)" },
  // ===== PHASE 2: EXECUTION (Days 14-44) — Active outreach + iteration =====
  { id:"e1", owner:"Annie", phase:2, cat:"content", title:"Publish a 'why I'm building Quietly' story post",
    hyp:"People follow founders, not companies. Your story creates connection.",
    action:"Post about Dion's frustration, your background, why you care. Include a vulnerable moment. End with a question.",
    measure:"Engagement vs intro post. Comments that show connection?",
    credit:"📕 DOAC Law 7 — Self-Story" },
  { id:"e2", owner:"Annie", phase:2, cat:"content", title:"Post a hot take on your industry",
    hyp:"Mild controversy gets 3x engagement of generic advice.",
    action:"Pick a common belief in RE/clinics you disagree with. Post your counter-view with reasoning. 'Unpopular opinion: X doesn't work because...'",
    measure:"Impressions vs previous posts. Disagreement is good — it's engagement.",
    credit:"📕 DOAC Law 11 — Avoid Wallpaper" },
  { id:"e3", owner:"Annie", phase:2, cat:"outreach", title:"Comment on 10 ideal clients' posts",
    hyp:"Genuine comments > connection requests for visibility.",
    action:"Find 10 RE brokers or clinic owners who post. Leave real comments — add insight, ask a question, share experience. Not 'Great post!'",
    measure:"Profile visits from comments. Any replies starting conversation?",
    credit:"📕 DOAC Law 3 — Common Ground" },
  { id:"e4", owner:"Annie", phase:2, cat:"content", title:"Test short-form vs long-form",
    hyp:"Short punchy posts sometimes outperform long stories.",
    action:"Post A: 10-sentence story. Post B: 3-sentence insight. Same topic. Compare engagement.",
    measure:"Impressions, comments, saves for each. Which format fits your voice?",
    credit:"📕 DOAC Law 19 — Sweat the Small Stuff" },
  { id:"e5", owner:"Annie", phase:2, cat:"outreach", title:"Send 5 DMs to warm connections",
    hyp:"Don't wait for perfect — start conversations.",
    action:"Use your 3-touch sequence on 5 people who accepted connections. Just message 1 — the intro. Track responses.",
    measure:"Reply rate. Any conversations started?",
    credit:"📕 DOAC Law 1 — Fill Your Five Buckets" },
  { id:"e6", owner:"Annie", phase:2, cat:"psychology", title:"Interview Dion and post his story",
    hyp:"Third-person storytelling about a cofounder is different and interesting.",
    action:"Write about Dion's 9 years in RE, what broke him, what he built. Position yourself as the storyteller. People will relate.",
    measure:"Engagement from people who didn't engage with your story?",
    credit:"📕 DOAC Law 7 — Self-Story" },
  { id:"e7", owner:"Annie", phase:2, cat:"content", title:"Post behind-the-scenes of building",
    hyp:"People love process content — it builds trust and anticipation.",
    action:"'Today we're building X. Here's the messy middle.' Screenshot or photo. Don't make it look polished.",
    measure:"Engagement, questions about the product, DMs.",
    credit:"📕 DOAC Law 13 — Show, Don't Tell" },
  { id:"e8", owner:"Annie", phase:2, cat:"content", title:"Repurpose a Dion Loom into a text post",
    hyp:"Same content, different format = new audience.",
    action:"Take Dion's 2-min demo, transcribe key points, turn into a LinkedIn post about the problem + solution.",
    measure:"Impressions. Did text-only reach different people?",
    credit:"Repurposing strategy" },
  { id:"e9", owner:"Annie", phase:2, cat:"outreach", title:"Ask for 3 introductions",
    hyp:"Referrals convert 5-10x cold outreach.",
    action:"Message 3 warm connections: 'Love how you approach [X]. Anyone in your network who struggles with admin and might be open to a 15-min chat?'",
    measure:"Intros received. Conversion rate.",
    credit:"📕 DOAC Law 1 — Five Buckets" },
  { id:"e10", owner:"Annie", phase:2, cat:"psychology", title:"Reflect on what's working",
    hyp:"Weekly reflection prevents drift and builds confidence.",
    action:"Journaling: What got engagement? What felt natural? What flopped but you learned from? Adjust next week's plan.",
    measure:"1 page of notes. 3 specific adjustments identified.",
    credit:"📗 Atomic Habits — Reflection" },
  { id:"e11", owner:"Dion", phase:2, cat:"outreach", title:"Send 10 warm outreach messages",
    hyp:"Warm outreach converts 5-10x cold.",
    action:"Message 10 from your broker network. 'Hey [name], building something for RE admin. Can I get 15 min of your brain?' Personalize each.",
    measure:"Reply rate. Conversations started?",
    credit:"📕 DOAC Law 3 — Common Ground" },
  { id:"e12", owner:"Dion", phase:2, cat:"outreach", title:"Send 10 cold emails",
    hyp:"Cold works at volume. Test the winning subject line.",
    action:"Use subject line winner. 10 emails to brokers you don't know. Simple ask: quick call about automation.",
    measure:"Open rate, reply rate. Any calls booked?",
    credit:"📕 DOAC Law 18 — First 5 Seconds" },
  { id:"e13", owner:"Dion", phase:2, cat:"product", title:"Julia discovery call — run the questions",
    hyp:"Structured discovery surfaces real pain.",
    action:"Use your 10 prepared questions. Ask, listen, don't pitch. Take notes verbatim. This is gold.",
    measure:"3+ pain points identified? Clear next steps agreed?",
    credit:"Mom Test" },
  { id:"e14", owner:"Dion", phase:2, cat:"product", title:"Send Julia follow-up + proposal outline",
    hyp:"Fast follow-up shows professionalism.",
    action:"Within 24hr: 'Great call. Here's what I heard, here's what I'd propose.' Bullet point summary + rough scope.",
    measure:"Reply received. Next step scheduled?",
    credit:"SPIN Selling" },
  { id:"e15", owner:"Dion", phase:2, cat:"outreach", title:"Test 'pain statement' vs 'benefit statement' email opener",
    hyp:"Pain pulls harder than gain.",
    action:"A: 'Filing documents manually is eating your day' B: 'What if documents filed themselves?' 5 emails each.",
    measure:"Reply rate comparison.",
    credit:"📕 DOAC Law 5 — Talk to the Elephant" },
  { id:"e16", owner:"Dion", phase:2, cat:"process", title:"Track outreach in a spreadsheet",
    hyp:"What gets measured gets managed.",
    action:"Create simple tracker: Name, Date reached, Method, Response, Status. Update daily. Review weekly.",
    measure:"Dashboard created? Actually using it?",
    credit:"Sales process basics" },
  { id:"e17", owner:"Dion", phase:2, cat:"outreach", title:"Reach out via 1 different channel",
    hyp:"Email/LinkedIn fatigue is real. Try something else.",
    action:"Try: voice note on LinkedIn, short video DM, or even SMS if you have their number. Same message, different format.",
    measure:"Reply rate vs text messages.",
    credit:"📕 DOAC Law 11 — Avoid Wallpaper" },
  { id:"e18", owner:"Dion", phase:2, cat:"product", title:"Create Julia spec doc from discovery call",
    hyp:"Spec doc reduces misalignment.",
    action:"Document: what exactly gets built, what's out of scope, timeline, price, success criteria. Send for approval before building.",
    measure:"Spec approved? Both sides aligned?",
    credit:"Running Lean" },
  { id:"e19", owner:"Dion", phase:2, cat:"psychology", title:"Write your rejection shield",
    hyp:"Pre-planning for rejection reduces pain.",
    action:"Privately write: 'Every no is data. I need 20 nos to get to 1 yes. Each rejection sharpens the pitch.' Revisit when rejected.",
    measure:"Did you reframe rejections this week?",
    credit:"📕 DOAC Law 23 — Never Fight Emotion" },
  { id:"e20", owner:"Dion", phase:2, cat:"outreach", title:"Ask 1 'no' for feedback",
    hyp:"Polite 'why not' reveals real objections.",
    action:"Anyone who didn't reply or said no: 'Totally understand. Curious — was it bad timing, not a problem for you, or something else?'",
    measure:"Any feedback received? Pattern emerging?",
    credit:"Mom Test" },
  { id:"e21", owner:"Dion", phase:2, cat:"outreach", title:"Follow up with every warm lead",
    hyp:"Most deals close on follow-up 4-7, not the first touch.",
    action:"Anyone who replied but didn't book: 'Just bumping this up — does [day/time] work?' Be polite, persistent.",
    measure:"Meetings booked from follow-ups.",
    credit:"Sales follow-up research" },
  { id:"e22", owner:"Dion", phase:2, cat:"product", title:"Start Julia build sprint",
    hyp:"Deliver proof of value ASAP to maintain momentum.",
    action:"Block 3 hours. Build the core workflow. Document as you go — this becomes onboarding for future clients.",
    measure:"Core workflow functional? Demo-able?",
    credit:"Shape Up" },
  { id:"e23", owner:"Dion", phase:2, cat:"process", title:"Weekly outreach numbers review",
    hyp:"Weekly numbers reveal what's working.",
    action:"End of week: how many sent, how many replied, how many calls. Calculate rates. Where's the bottleneck?",
    measure:"Bottleneck identified? 1 adjustment for next week.",
    credit:"Sales metrics basics" },
  { id:"e24", owner:"Dion", phase:2, cat:"outreach", title:"Test 'social proof' in email",
    hyp:"Even early traction counts as proof.",
    action:"Add one line: 'Currently building this for [industry] broker in Montreal.' Test vs emails without. Honest even if it's Julia.",
    measure:"Reply rate difference.",
    credit:"📕 DOAC Law 12 — Social Proof" },
  { id:"e25", owner:"Dion", phase:2, cat:"psychology", title:"Morning ritual before outreach",
    hyp:"Mindset affects action. 5 min prep prevents avoidance.",
    action:"Before sending: 5 min breathwork or review your 'why'. Then immediate action — no tabs, no email check first.",
    measure:"Did outreach feel easier? Did you follow through?",
    credit:"📗 Atomic Habits — Environment + 📕 DOAC Law 22" },
  { id:"e26", owner:"Dion", phase:2, cat:"outreach", title:"Reach out to someone 'too big'",
    hyp:"Big targets are less competitive — everyone assumes they won't respond.",
    action:"Find 1 broker who's 'too successful' for you to approach. Send the same outreach. Worst case: no reply.",
    measure:"Did you send it? Any response?",
    credit:"📕 DOAC Law 33 — Short-Term Sacrifice" },
  // ===== PHASE 3: LEVERAGE (Days 45-60) — Case study, referrals, authority =====
  { id:"l1", owner:"Dion", phase:3, cat:"product", title:"Document Julia results",
    hyp:"Measured results = case study = sales tool.",
    action:"Track time saved, errors prevented, satisfaction. Create simple before/after comparison. Get Julia's quote.",
    measure:"3+ data points recorded? Client quote obtained?",
    credit:"📕 DOAC Law 13 — Show, Don't Tell" },
  { id:"l2", owner:"Dion", phase:3, cat:"content", title:"Write Julia case study",
    hyp:"1 good case study > 100 cold emails.",
    action:"Problem → Process → Outcome → Quote. One page. Before/after screenshots. Share with Annie for LinkedIn version.",
    measure:"Case study done? Visual and written?",
    credit:"StoryBrand" },
  { id:"l3", owner:"Dion", phase:3, cat:"outreach", title:"Ask Julia for 3 referrals",
    hyp:"Happy clients are your best sales channel.",
    action:"'Who do you know who's drowning in the same admin you were?' Ask for intros, not just names.",
    measure:"Intros received. Conversations started.",
    credit:"📕 DOAC Law 1 — Five Buckets" },
  { id:"l4", owner:"Annie", phase:3, cat:"content", title:"Post the Julia win",
    hyp:"Public wins attract similar clients.",
    action:"'We just finished building X for Julia. Here's what it does... If you're struggling with Y, let's talk.' Include numbers.",
    measure:"DMs from post. Calls booked.",
    credit:"📕 DOAC Law 13 — Show, Don't Tell" },
  { id:"l5", owner:"Dion", phase:3, cat:"process", title:"Systematize Julia delivery for next client",
    hyp:"Document once, deliver faster every time.",
    action:"Create checklist: discovery questions, spec template, build steps, training agenda, handoff process.",
    measure:"Checklist done? Would next client go 50% faster?",
    credit:"E-Myth Revisited" },
  { id:"l6", owner:"Dion", phase:3, cat:"product", title:"Add 1 feature Julia requested",
    hyp:"Client-requested features = proven demand.",
    action:"Pick 1 thing Julia asked for. Build it. Ask: 'Worth extra?' This could be a paid upgrade.",
    measure:"Feature built? Client response?",
    credit:"Running Lean" },
  { id:"l7", owner:"Annie", phase:3, cat:"outreach", title:"10 more connection requests using case study",
    hyp:"Social proof in the request increases acceptance.",
    action:"'Just built AI automation for a Montreal broker — saved 10 hrs/week. Would love to connect.'",
    measure:"Acceptance rate vs phase 1 requests?",
    credit:"📕 DOAC Law 12 — Social Proof" },
  { id:"l8", owner:"Dion", phase:3, cat:"outreach", title:"Email cold list with case study link",
    hyp:"Case study = permission to follow up.",
    action:"Re-email everyone who didn't reply. 'Quick update — just finished a build for a Montreal broker. Case study attached. Worth a 10-min call?'",
    measure:"Reply rate vs original cold emails.",
    credit:"📕 DOAC Law 13 — Show, Don't Tell" },
  { id:"l9", owner:"Annie", phase:3, cat:"content", title:"Post 'lessons learned from first client'",
    hyp:"Transparency builds trust and engagement.",
    action:"'3 things we learned building for Julia: (1) X (2) Y (3) Z.' Honest, specific, helpful.",
    measure:"Engagement. Questions about working together?",
    credit:"📕 DOAC Law 7 — Self-Story" },
  { id:"l10", owner:"Dion", phase:3, cat:"process", title:"Create onboarding doc for client 2",
    hyp:"Professional onboarding = higher perceived value.",
    action:"Welcome email, timeline, expectations, contact points. Template it for future clients.",
    measure:"Doc created? Ready to send to next client?",
    credit:"E-Myth Revisited" },
  { id:"l11", owner:"Annie", phase:3, cat:"content", title:"Record video testimonial request to Julia",
    hyp:"Video testimonial is 5x written.",
    action:"'Julia, would you record a 30-sec video about working with us? I'll send 3 questions.' Send script/prompts.",
    measure:"Video received?",
    credit:"📕 DOAC Law 12 — Social Proof" },
  { id:"l12", owner:"Dion", phase:3, cat:"outreach", title:"Raise price 20% for next proposal",
    hyp:"Early clients underpriced. Test higher anchor.",
    action:"Next proposal: increase your price 20%. Same value, higher confidence. Track response.",
    measure:"Did client push back? Accept? Your confidence level?",
    credit:"Value-Based Fees" },
  { id:"l13", owner:"Annie", phase:3, cat:"outreach", title:"Run a mini experiment: offer free audit",
    hyp:"Free audits create conversations without sales pressure.",
    action:"Post or DM: '15-min free audit: I'll find the 1 automation that would save you the most time.' 10 people.",
    measure:"Take-up rate. Conversions to paid.",
    credit:"Lead magnet strategy" },
  { id:"l14", owner:"Dion", phase:3, cat:"product", title:"Build a 'Quick Win' package",
    hyp:"Low-commitment entry point gets foot in door.",
    action:"Define: what can you deliver in 1 week for a flat $X fee? Document scope. Use this for objections about 'too big a commitment.'",
    measure:"Package defined? Price set?",
    credit:"Value-Based Fees" },
];
